### ISSUE TITLE
Extension fails to activate

### ISSUE THREAD

**Issue by hymced** [McSodbrenner/vscode-better-open-editors#29]
Hello

```
2024-11-06 18:29:17.483 [error] Activating extension McSodbrenner.better-open-editors failed due to an error:
2024-11-06 18:29:17.483 [error] TypeError: Cannot read properties of undefined (reading 'replace')
	at new File (/Users/***/.vscode/extensions/mcsodbrenner.better-open-editors-1.11.2/src/TreeItem/File.js:83:48)
	at #addTab (/Users/***/.vscode/extensions/mcsodbrenner.better-open-editors-1.11.2/src/treeviewPanel.js:263:16)
	at /Users/***/.vscode/extensions/mcsodbrenner.better-open-editors-1.11.2/src/treeviewPanel.js:136:16
	at Array.forEach (<anonymous>)
	at TreeviewPanel.recreateTree (/Users/***/.vscode/extensions/mcsodbrenner.better-open-editors-1.11.2/src/treeviewPanel.js:124:8)
	at new TreeviewPanel (/Users/***/.vscode/extensions/mcsodbrenner.better-open-editors-1.11.2/src/treeviewPanel.js:26:8)
	at activate (/Users/***/.vscode/extensions/mcsodbrenner.better-open-editors-1.11.2/src/extension.js:7:24)
```

I can give you more details if needed!

macOS: Sonoma 14.6.1
vscode: v1.95.1 (october 2024)

**Comment by McSodbrenner** [comment]
That would be great. The reason should be some kind of file that hasn't been handled so far. Do you have any idea which file that could be?

**Comment by hymced** [comment]
Hey
No, my editors changed quite a lot since last time, I have just enabled the extension back again, and now it activates just fine! I will try to investigate later, I used another extension to saves my tabs before closing them all last time, so I might be able to check if one in particular was messing things up.
But now I have another issue: some files are not properly placed in folders. For example the files under `src/components` are, but not those in some/other/folder. between the folders and the files that are not organized in folders are `.some_root_files`" and `package.json` for example, I don't know if helps :/
